# Generated by Django 5.0.6 on 2024-12-22 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('isleyis', '0003_product_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
