# Generated by Django 5.0.6 on 2024-12-25 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('isleyis', '0004_alter_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='email',
            field=models.EmailField(max_length=254, null=True, unique=True),
        ),
    ]
