# Generated by Django 5.0.6 on 2024-12-29 10:54

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('isleyis', '0005_customer_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='elapsed_time',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='order',
            name='order_received_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='order',
            name='priority_score',
            field=models.FloatField(default=0.0),
        ),
    ]
